### ISSUE TITLE
Failed to get file list can't detect virtual sd card.

### ISSUE THREAD

**Issue by wormiedk** [Stephan3/dwc2-for-klipper-socket#21]
I get the following in /tmp/dwc2.log
`
========== Started ==========
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop ob
ject at 0x760711f0>>, <Task finished coro=<read_stream() done, defined at /home/pi/dwc2-for-klipper-socket/web_dwc2.py:174> exception=TypeError("the JSON obj
ect must be str, not 'bytes'",)>)
Traceback (most recent call last):
  File "/home/pi/dwc-env/lib/python3.5/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/pi/dwc-env/lib/python3.5/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/dwc2-for-klipper-socket/web_dwc2.py", line 181, in read_stream
    out_ = json.loads(data[:-1])
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
`

**Comment by Stephan3** [comment]
By doing what?

**Comment by wormiedk** [comment]
When launching DWC. The web interface hangs with the "failed to get file list" and "can't detect virtual sd card" messages
<img width="590" alt="Skærmbillede 2021-01-20 133849" src="https://user-images.githubusercontent.com/4417857/105175979-eb537e80-5b24-11eb-98b0-256a95b27989.png">

**Comment by Stephan3** [comment]
show us your klippy.log and dwc.log . we cant "guess"

**Comment by Apar7777** [comment]
Hello
Same issue for me
Klipper and dcw are launched by systemd

 Added -a /tmp/klippy_uds in klipper.service

 Added in config: (is that correct ?)
[virtual_sdcard]
path = /home/pi/sdcard

Klipper run well with octoprint (octopi distrib)

![ScreenShot060](https://user-images.githubusercontent.com/78183455/106214065-514ba000-61ce-11eb-9999-81c67d578912.png)

[dwc2.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5890758/dwc2.log)

[klippy.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5890759/klippy.log)

**Comment by Van-Hellsing** [comment]
Check the printer.cfg file it may be empty

**Comment by Stephan3** [comment]
> Hello
> Same issue for me
> Klipper and dcw are launched by systemd
> 
> Added -a /tmp/klippy_uds in klipper.service
> 
> Added in config: (is that correct ?)
> [virtual_sdcard]
> path = /home/pi/sdcard
> 
> Klipper run well with octoprint (octopi distrib)
> 
> 
> [dwc2.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5890758/dwc2.log)
> 
> [klippy.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5890759/klippy.log)

looks correct to me. I il ltry your configuration locally.

**Comment by adq** [comment]
Hey, maybe the original commenter didn't realise you have to setup the virtual sd card in *klipper* config not in dwc.cfg. 

Had the same problem and adding this in klipper sorted it completely:
```
[virtual_sdcard]
path: /home/pi/sdcard/
```
