### ISSUE TITLE
async def init_(self):

### ISSUE THREAD

**Issue by asovetov** [Stephan3/dwc2-for-klipper-socket#23]
Clear install, all latest, raspberry 4, Octopi.  
  
  
 ````
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 146, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 139, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 119, in load_object
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/klipper/klippy/extras/web_dwc2.py", line 72
    async def init_(self):
````

**Comment by dmmedia** [comment]
Remove [web_dwc2] section from klippers config and start dwc2 as a separate service.
