### ISSUE TITLE
Failed to get file list: Target drive is unmounted, Can't detect virtual sdcard

### ISSUE THREAD

**Issue by sealj553** [Stephan3/dwc2-for-klipper-socket#4]
Hi,
I just installed this with th33xitus's installer, and it looks like everything is working as intended, but when I try to upload files, I get the following errors on the bottom right:
```
Failed to get file list: Target drive is unmounted
```
```
Can't detect virtual sdcard
```
I tried with and without virtual_sd enabled.
I did get it to print once by hitting `Upload & Start`, but it no longer works and I don't know what changed. I've never been able to upload files through the `Jobs` tab, though.

Relevant section of my `printer.cfg`:
```
[virtual_sdcard]
path: /home/pi/sdcard
```
This used to be an Octoprint install, but I gutted it. I don't think I left anything enabled that should interfere. I also went through the installation instructions after using the script and made sure everything is set up correct.
Let me know if there are any relevant logs I can include.
Thanks for all the hard work on this project!

**Comment by Stephan3** [comment]
Hi!

Can sounds like an issue with your folder. Can you recheck that everything is fine with /home/pi/sdcard?
might be nonexistent? or just remove it and recreate as a pi user?
During startup the first few seconds not all klipperdata is present. The webif is throwing that error then but weverything works fine.

**Comment by sealj553** [comment]
The `/home/pi/sdcard` directory does indeed exist. I've also tried to `chmod -R 777` and `chown -R pi:pi` it just in case, no luck. I've also tried  creating `/home/pi/jobs` directory for instance, with the same result.
I just confirmed my installation got extra borked, so I'm going to reinstall from scratch manually and see how it goes.

**Comment by Stephan3** [comment]
try running it from console. enter the directory where your web_dwc2.py is located and rut it using python3 we_dwc2.py

**Comment by sealj553** [comment]
Just reinstalled fresh. Not sure if this is the same issue, but:
```
pi@printer:~/dwc2-for-klipper-socket $ python3 web_dwc2.py
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0xb5d3beb0>>, <Task finished coro=<dwc2.init_() done, defined at web_dwc2.py:150> exception=TypeError('expected str, bytes or os.PathLike object, not NoneType')>)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/pi/.local/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "web_dwc2.py", line 181, in init_
    self.sd_root = os.path.expanduser( configfile.get('config',{}).get('virtual_sdcard',{}).get('path', None) )
  File "/usr/lib/python3.7/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
The process doesn't exit, but there's no web interface.

**Comment by Stephan3** [comment]
looks like your virtual sdcard is not recognized. give us. please login to console and give us the polldata:
curl http://127.0.0.1:4700/rr_poll_data

**Comment by sealj553** [comment]
I ran `python3 web_dwc2.py` in another shell, then:
```
pi@printer:~ $ curl http://127.0.0.1:4700/rr_poll_data
curl: (7) Failed to connect to 127.0.0.1 port 4700: Connection refused
```
Looks like the server isn't running. Am I missing something?

**Comment by Stephan3** [comment]
Wrong port sorry 4750

**Comment by sealj553** [comment]
```
pi@printer:~ $ curl http://127.0.0.1:4750/rr_poll_data
{"last_path": null, "klipper_macros": [], "gcode/help": {"STATUS": "Report the printer status", "SAVE_CONFIG": "Overwrite config file and restart", "RESTART": "Reload config file and restart host software", "FIRMWARE_RESTART": "Restart firmware, host, and reload config"}, "info": {"state_message": "Unable to open config file /home/pi/printer.cfg\nOnce the underlying issue is corrected, use the \"RESTART\"\ncommand to reload the config and restart the host software.\nPrinter is halted\n", "klipper_path": "/home/pi/klipper", "config_file": "/home/pi/printer.cfg", "software_version": "v0.8.0-786-g063f9a2c", "hostname": "printer", "cpu_info": "4 core ARMv7 Processor rev 3 (v7l)", "state": "error", "python_path": "/home/pi/klippy-env/bin/python", "log_file": "/tmp/klippy.log"}, "objects/list": {"objects": ["webhooks", "configfile"]}, "list_endpoints": {"endpoints": ["info", "list_endpoints", "emergency_stop", "gcode/restart", "gcode/subscribe_output", "objects/query", "objects/list", "gcode/firmware_restart", "objects/subscribe", "gcode/script", "gcode/help"]}, "gcode/subscribe_output": {}, "webhooks": {"state": "error", "state_message": "Unable to open config file /home/pi/printer.cfg\nOnce the underlying issue is corrected, use the \"RESTART\"\ncommand to reload the config and restart the host software.\nPrinter is halted\n"}, "configfile": {"config": {}}}
```
Now this problem is much clearer: `Unable to open config file /home/pi/printer.cfg`
Dumb error on my part, I forgot to copy over my config.

Now, it looks like it's working under the hood:
```
pi@printer:~/dwc2-for-klipper-socket $ curl localhost:4750/rr_poll_data
{"last_path": null, "klipper_macros": ["G29"], "gcode/help": {"SDCARD_RESET_FILE": "Clears a loaded SD File. Stops the print if necessary", "RESTORE_GCODE_STATE": "Restore a previously saved G-Code state", "BLTOUCH_STORE": "Store an output mode in the BLTouch EEPROM", "QUERY_ADC": "Report the last value of an analog pin", "TUNING_TOWER": "Tool to adjust a parameter at each Z height", "SAVE_CONFIG": "Overwrite config file and restart", "SET_DISPLAY_GROUP": "Set the active display group", "G29": "G-Code macro", "SAVE_GCODE_STATE": "Save G-Code coordinate state", "SET_PRESSURE_ADVANCE": "Set pressure advance parameters", "SET_GCODE_OFFSET": "Set a virtual offset to g-code positions", "PID_CALIBRATE": "Run PID calibration test", "INIT_TMC": "Initialize TMC stepper driver registers", "QUERY_PROBE": "Return the status of the z-probe", "BED_MESH_OUTPUT": "Retrieve interpolated grid of probed z-points", "TURN_OFF_HEATERS": "Turn off all heaters", "SET_STEPPER_ENABLE": "Enable/disable individual stepper by name", "QUERY_ENDSTOPS": "Report on the status of each endstop", "SET_TMC_CURRENT": "Set the current of a TMC driver", "Z_ENDSTOP_CALIBRATE": "Calibrate a Z endstop", "MANUAL_PROBE": "Start manual probe helper script", "DUMP_TMC": "Read and display TMC stepper driver registers", "PROBE_ACCURACY": "Probe Z-height accuracy at current XY position", "STATUS": "Report the printer status", "SDCARD_PRINT_FILE": "Loads a SD file and starts the print.  May include files in subdirectories.", "BLTOUCH_DEBUG": "Send a command to the bltouch for debugging", "SET_TMC_FIELD": "Set a register field of a TMC driver", "FIRMWARE_RESTART": "Restart firmware, host, and reload config", "STEPPER_BUZZ": "Oscillate a given stepper to help id it", "BED_MESH_CLEAR": "Clear the Mesh so no z-adjusment is made", "SET_GCODE_VARIABLE": "Set the value of a G-Code macro variable", "SET_VELOCITY_LIMIT": "Set printer velocity limits", "SET_PIN": "Set the value of an output pin", "SET_HEATER_TEMPERATURE": "Sets a heater temperature", "BED_MESH_PROFILE": "Bed Mesh Persistent Storage management", "PROBE": "Probe Z-height at current XY position", "BED_MESH_MAP": "Serialize mesh and output to terminal", "SET_EXTRUDER_STEP_DISTANCE": "Set extruder step distance", "PROBE_CALIBRATE": "Calibrate the probe's z_offset", "BED_MESH_CALIBRATE": "Perform Mesh Bed Leveling", "RESTART": "Reload config file and restart host software", "ACTIVATE_EXTRUDER": "Change the active extruder"}, "info": {"state_message": "Section 'web_dwc2' is not a valid config section\nOnce the underlying issue is corrected, use the \"RESTART\"\ncommand to reload the config and restart the host software.\nPrinter is halted\n", "klipper_path": "/home/pi/klipper", "config_file": "/home/pi/printer.cfg", "software_version": "v0.8.0-786-g063f9a2c", "hostname": "printer", "cpu_info": "4 core ARMv7 Processor rev 3 (v7l)", "state": "error", "python_path": "/home/pi/klippy-env/bin/python", "log_file": "/tmp/klippy.log"}, "objects/list": {"objects": ["webhooks", "configfile", "probe", "gcode_move", "bed_mesh", "heaters", "heater_bed", "heater_fan nozzle_cooling_fan", "fan", "menu", "display_status", "output_pin beeper", "gcode_macro G29", "print_stats", "virtual_sdcard", "query_endstops", "idle_timeout", "toolhead", "extruder"]}, "list_endpoints": {"endpoints": ["info", "list_endpoints", "query_endstops/status", "emergency_stop", "gcode/restart", "gcode/subscribe_output", "objects/query", "objects/list", "gcode/firmware_restart", "objects/subscribe", "gcode/script", "gcode/help"]}, "gcode/subscribe_output": {}, "heaters": {"available_sensors": ["heater_bed", "extruder"], "available_heaters": ["heater_bed", "extruder"]}, "heater_fan nozzle_cooling_fan": {"speed": 0.0}, "bed_mesh": {"mesh_max": [0.0, 0.0], "mesh_matrix": [[]], "profile_name": "", "mesh_min": [0.0, 0.0], "probed_matrix": [[]]}, "gcode_move": {"homing_origin": [0.0, 0.0, 0.0, 0.0], "speed_factor": 1.0, "gcode_position": [0.0, 0.0, 0.0, 0.0], "absolute_extrude": true, "absolute_coordinates": true, "position": [0.0, 0.0, 0.0, 0.0], "speed": 1500.0, "extrude_factor": 1.0}, "menu": {"running": false, "rows": 4, "cols": 16, "timeout": 0}, "gcode_macro G29": {}, "probe": {"last_query": false}, "print_stats": {"print_duration": 0.0, "total_duration": 0.0, "filament_used": 0.0, "filename": "", "state": "standby", "message": ""}, "output_pin beeper": {"value": 0.0}, "idle_timeout": {"state": "Idle", "printing_time": 0.0}, "query_endstops": {"last_query": {}}, "fan": {"speed": 0.0}, "configfile": {"config": {"tmc2209 extruder": {"uart_address": "3", "stealthchop_threshold": "5", "run_current": "0.675", "microsteps": "16", "uart_pin": "PC11", "hold_current": "0.500", "tx_pin": "PC10"}, "board_pins": {"aliases": "\nEXP1_1=PB5, EXP1_3=PA9,   EXP1_5=PA10, EXP1_7=PB8, EXP1_9=<GND>,\nEXP1_2=PA15, EXP1_4=<RST>, EXP1_6=PB9,  EXP1_8=PB15, EXP1_10=<5V>"}, "safe_z_home": {"z_hop_speed": "30.0", "speed": "120.0", "home_xy_position": "120,140", "z_hop": "10.0"}, "output_pin beeper": {"pin": "EXP1_1"}, "heater_bed": {"control": "pid", "pid_kp": "54.027", "sensor_pin": "PC3", "heater_pin": "PC9", "sensor_type": "ATC Semitec 104GT-2", "pid_kd": "948.182", "pid_ki": "0.770", "min_temp": "0", "max_temp": "130"}, "virtual_sdcard": {"path": "/home/pi/sdcard/gcodes"}, "web_dwc2": {"printer_name": "Ender3", "listen_adress": "0.0.0.0", "web_path": "web", "listen_port": "4750"}, "stepper_z": {"position_endstop": "0.0", "position_max": "235", "endstop_pin": "probe:z_virtual_endstop", "step_pin": "PB0", "dir_pin": "PC5", "step_distance": ".0025", "enable_pin": "!PB1"}, "stepper_y": {"position_endstop": "0", "position_max": "235", "endstop_pin": "^PC1", "step_pin": "PB10", "homing_speed": "50", "dir_pin": "!PB2", "step_distance": ".0125", "enable_pin": "!PB11"}, "stepper_x": {"position_endstop": "0", "position_max": "235", "endstop_pin": "^PC0", "step_pin": "PB13", "homing_speed": "50", "dir_pin": "!PB12", "step_distance": ".0125", "enable_pin": "!PB14"}, "static_digital_output usb_pullup_enable": {"pins": "!PA14"}, "mcu": {"baud": "921600", "serial": "/dev/serial/by-id/usb-Klipper_stm32f103xe_31FFD7054248313021590757-if00"}, "printer": {"max_velocity": "500", "max_z_velocity": "5", "kinematics": "cartesian", "max_accel": "5000", "max_z_accel": "100"}, "heater_fan nozzle_cooling_fan": {"pin": "PC6"}, "fan": {"pin": "PC7"}, "tmc2209 stepper_z": {"uart_address": "1", "stealthchop_threshold": "5", "run_current": "0.600", "microsteps": "16", "uart_pin": "PC11", "hold_current": "0.500", "tx_pin": "PC10"}, "tmc2209 stepper_x": {"uart_address": "0", "stealthchop_threshold": "250", "run_current": "0.600", "microsteps": "16", "uart_pin": "PC11", "hold_current": "0.500", "tx_pin": "PC10"}, "tmc2209 stepper_y": {"uart_address": "2", "stealthchop_threshold": "250", "run_current": "0.600", "microsteps": "16", "uart_pin": "PC11", "hold_current": "0.500", "tx_pin": "PC10"}, "bed_mesh": {"horizontal_move_z": "4", "mesh_pps": "2,2", "mesh_min": "10,10", "mesh_max": "170,180", "fade_start": "1.0", "probe_count": "3,3", "speed": "120"}, "display": {"click_pin": "^!EXP1_2", "cs_pin": "EXP1_7", "encoder_pins": "^EXP1_5, ^EXP1_3", "lcd_type": "st7920", "sid_pin": "EXP1_8", "sclk_pin": "EXP1_6"}, "bltouch": {"sensor_pin": "^PC2", "control_pin": "PA1", "pin_move_time": "0.4", "y_offset": "-15", "x_offset": "-40", "z_offset": "1.15"}, "gcode_macro G29": {"gcode": "\nBED_MESH_CALIBRATE\nBED_MESH_PROFILE SAVE=p1\nG1 X0 Y0 Z5 F4000"}, "extruder": {"control": "pid", "pid_kp": "21.527", "sensor_type": "EPCOS 100K B57560G104F", "sensor_pin": "PA0", "nozzle_diameter": "0.400", "pressure_advance_smooth_time": "0.02", "heater_pin": "PC8", "pressure_advance": "0.05", "max_extrude_only_distance": "100", "step_pin": "PB3", "pid_kd": "108.982", "min_temp": "0", "pid_ki": "1.063", "filament_diameter": "1.750", "dir_pin": "!PB4", "max_temp": "250", "step_distance": "0.00240963855421686747", "enable_pin": "!PD2"}}}, "display_status": {"progress": 0.0, "message": null}, "toolhead": {"square_corner_velocity": 5.0, "max_accel": 5000.0, "homed_axes": "", "estimated_print_time": 0.0, "max_velocity": 500.0, "print_time": 0.001, "max_accel_to_decel": 2500.0, "position": [0.0, 0.0, 0.0, 0.0], "extruder": "extruder"}, "webhooks": {"state": "error", "state_message": "Section 'web_dwc2' is not a valid config section\nOnce the underlying issue is corrected, use the \"RESTART\"\ncommand to reload the config and restart the host software.\nPrinter is halted\n"}, "virtual_sdcard": {"progress": 0.0, "is_active": false, "file_position": 0}, "heater_bed": {"temperature": 0.0, "target": 0.0}, "extruder": {"pressure_advance": 0.05, "target": 0.0, "temperature": 0.0, "smooth_time": 0.02}}
```


Now it's running without error. Though when I try to `http://192.168.1.164:4750/`, I get `500: Internal Server Error`

**Comment by Stephan3** [comment]
@sealj553 as stated above, run from console, i cant guess whats on.

EDIT:
there is a output now to /tmp/dwc2.log

pull latest master

**Comment by sealj553** [comment]
Right, my bad.
I unplugged my printer, restarted the klipper service, and tried again. Now the interface is working:

```
pi@printer:~/dwc2-for-klipper-socket $ python3 web_dwc2.py
DWC2:.1510239 - 192.168.1.149 - GET - /
DWC2:.3936486 - 192.168.1.149 - GET - /css/app.c3eac487.css
DWC2:.7278302 - 192.168.1.149 - GET - /js/app.289e2336.js
DWC2:.2660468 - 192.168.1.149 - GET - /rr_connect?password=reprap&time=2020-9-15T7%3A47%3A21
DWC2:.3660364 - 192.168.1.149 - GET - /fonts/materialdesignicons-webfont.a323c28e.woff2
DWC2:.4143388 - 192.168.1.149 - GET - /rr_download?name=0%3A%2Fsys%2Fdwc2settings.json
DWC2:.4651139 - 192.168.1.149 - GET - /rr_filelist?dir=0%3A%2Fmacros&first=0
DWC2:.4829457 - 192.168.1.149 - GET - /rr_download?name=0%3A%2Fsys%2Fdwc2defaults.json
DWC2:.7067943 - 192.168.1.149 - GET - /rr_filelist?dir=0%3A%2Fmacros&first=0
```
The logging is working by the way.

It's showing status: off, no axes, but looks like it's connected to klipper.
![Screenshot from 2020-09-15 07-59-00](https://user-images.githubusercontent.com/8863960/93207763-752fad00-f729-11ea-92db-db1921ab062c.png)

**Comment by Stephan3** [comment]
What is the result of status?
Enter status as gcode

**Comment by sealj553** [comment]
Kind of a dumb error again. It there was a syntax error in my klipper config because I had added a `[web_dwc2]` block.
Removing that and restarting klipper fixed that. It can now connect. I can also upload gcode files now. I have a print running now.
Though I am getting a lot of 500 errors, with the interface flashing between "Connection established" and "Connection interrupted..." rendering it unusable. Also "Failed to get file info" when I uploaded a gcode file.

Here's the log: https://pastebin.com/Lx4cziHQ

**Comment by Stephan3** [comment]
can you provide that gcode to me please?


top_front_.gcode

**Comment by sealj553** [comment]
Had to add extension so github would let me upload: [top_front_.gcode.txt](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5228553/top_front_.gcode.txt)

**Comment by Stephan3** [comment]
please check again latest master. feels safer now.

**Comment by sealj553** [comment]
It's working great now, thanks! Just started a print a few times to test, no errors at all.
I'll see if I can help with some documentation :)

**Comment by Alexdad76** [comment]
The same situation, I cannot connect to the printer (th33xitus's installer).
Status - Off 

[dwc2.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5250087/dwc2.log)
[klippy.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5250088/klippy.log)


PS: Before that, Octoprint worked fine.

System:
> Welcome to Ubuntu Xenial with Armbian Linux 3.4.113-sun8i
System load:   0.27 0.31 0.27   Up time:       1:00 hour
Memory usage:  27 % of 1000MB   IP:            192.168.1.67
CPU temp:      23°C
Usage of /:    32% of 15G
+ SKR 1.1

PS1 I'll try to reinstall another system based on Debian.

**Comment by Alexdad76** [comment]
> 
> 
> The same situation, I cannot connect to the printer (th33xitus's installer).
> Status - Off
> 
> [dwc2.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5250087/dwc2.log)
> [klippy.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5250088/klippy.log)
> 
> PS: Before that, Octoprint worked fine.
> 
> System:
> 
> > Welcome to Ubuntu Xenial with Armbian Linux 3.4.113-sun8i
> > System load:   0.27 0.31 0.27   Up time:       1:00 hour
> > Memory usage:  27 % of 1000MB   IP:            192.168.1.67
> > CPU temp:      23°C
> > Usage of /:    32% of 15G
> 
>     * SKR 1.1
> 
> 
> PS1 I'll try to reinstall another system based on Debian.

Armbian_20.08.1_Orangepipcplus_buster_current_5.8.5.img.xz  works but keeps giving error : HTTP request timed out

**Comment by Alexdad76** [comment]
> 
> 
> > The same situation, I cannot connect to the printer (th33xitus's installer).
> > Status - Off
> > [dwc2.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5250087/dwc2.log)
> > [klippy.log](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5250088/klippy.log)
> > PS: Before that, Octoprint worked fine.
> > System:
> > > Welcome to Ubuntu Xenial with Armbian Linux 3.4.113-sun8i
> > > System load:   0.27 0.31 0.27   Up time:       1:00 hour
> > > Memory usage:  27 % of 1000MB   IP:            192.168.1.67
> > > CPU temp:      23°C
> > > Usage of /:    32% of 15G
> > 
> > 
> > ```
> > * SKR 1.1
> > ```
> > 
> > 
> > PS1 I'll try to reinstall another system based on Debian.
> 
> Armbian_20.08.1_Orangepipcplus_buster_current_5.8.5.img.xz works but keeps giving error : HTTP request timed out

After some time, the error no longer appears.
